name: Trigger auto deployment for mvx-utils-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mvx-utils-api-AutoDeployTrigger-69521422-2417-4ee1-9962-14f200a109ba.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MVXUTILSAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MVXUTILSAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MVXUTILSAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/devnet.Dockerfile
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: mvxdataapi.azurecr.io
          registryUsername: ${{ secrets.MVXUTILSAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MVXUTILSAPI_REGISTRY_PASSWORD }}
          containerAppName: mvx-utils-api
          resourceGroup: mvx-ai-assitant
          imageToBuild: mvxdataapi.azurecr.io/mvx-utils-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


